"use client";

import "./globals.css";
import type { ReactNode } from "react";
import { StrictMode } from "react";
import { Toaster } from "react-hot-toast";
import {
    QueryClient,
    QueryClientProvider,
} from "@tanstack/react-query";

//export const metadata = {
//    title: "Next.js",
//    description: "Generated by Next.js",
//};

type Props = {
    readonly children: ReactNode;
};

export default function RootLayout({ children }: Props) {
    const queryClient = new QueryClient();

    return (
        <html lang="en">
            <body>
                <StrictMode>
                    <QueryClientProvider client={queryClient}>
                        <Toaster />
                        {children}
                    </QueryClientProvider>
                </StrictMode>
            </body>
        </html>
    );
}
